image: mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim

options:
  max-time: 15
pipelines:
  default:
    - parallel:
        - step:
            name: "Build/Test Web"
            script:
              - sleep 10
              - dotnet test SP21.P05.Tests.Web
            services:
              - sqlserver
        - step:
            name: "Build/Test Mobile"
            deployment: test-mobile
            image: node:alpine
            caches:
              - npm
            script:
              - apk add --no-cache bash
              - cd sp21-p05-Mobile
              - npm install -g expo-cli
              - yarn install --frozen-lockfile
              - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
              - expo publish --non-interactive --release-channel ci
  branches:
    master:
      - parallel:
          - step:
              name: "Build/Test/Publish Web"
              script:
                - apt-get update
                - apt-get install --yes zip
                - apt-get install --yes nodejs
                - apt-get install --yes npm
                - npm install -g yarn
                - sleep 10
                - dotnet test SP21.P05.Tests.Web
                - dotnet publish SP21.P05.Web --output publish
                - cd publish && zip -r web-$BITBUCKET_BUILD_NUMBER.zip .
              services:
                - sqlserver
              artifacts:
                - publish/*.zip
          - step:
              name: "Build/Test/Publish Expo"
              deployment: test-mobile
              image: node:alpine
              caches:
                - npm
              script:
                - apk add --no-cache bash
                - cd sp21-p05-Mobile
                - npm install -g expo-cli
                - yarn install --frozen-lockfile
                - expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
                - expo publish --non-interactive
                - expo build:android -t apk --no-wait --non-interactive
      - step:
          name: "Deploy to Azure"
          deployment: test
          script:
            - pipe: microsoft/azure-web-apps-deploy:1.0.0
              variables:
                AZURE_APP_ID: $AZURE_APP_ID
                AZURE_PASSWORD: $AZURE_PASSWORD
                AZURE_TENANT_ID: $AZURE_TENANT_ID
                AZURE_RESOURCE_GROUP: "sp21-p05-g01"
                AZURE_APP_NAME: "selu383-sp21-p05-g01"
                ZIP_FILE: "publish/web-$BITBUCKET_BUILD_NUMBER.zip"
      - step:
          name: "Check API Health"
          script:
            - curl -s https://selu383-sp21-p05-g01.azurewebsites.net/api/events
            - sleep 10
            - curl -sSf https://selu383-sp21-p05-g01.azurewebsites.net/api/events
      - step:
          name: "Check React Web Health"
          script:
            - curl -sSf https://selu383-sp21-p05-g01.azurewebsites.net/manifest.json

definitions:
  caches:
    npm: ~/.npm
  services:
    sqlserver:
      image: mcr.microsoft.com/mssql/server:2019-CU8-ubuntu-16.04
      memory: 2048
      variables:
        ACCEPT_EULA: Y
        SA_PASSWORD: Password123!
